import { Client, Certificate, Activity } from '@/types';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'client-1',
    contactName: 'Sarah Mitchell',
    businessName: 'Meridian Group LLC',
    contactEmail: 'sarah@meridiangroup.com',
    certificateCount: 4,
    avatarInitials: 'SM',
    phone: '(555) 234-5678',
    address: '100 Meridian Plaza, Suite 400, Chicago, IL 60601',
    createdAt: 'Jan 15, 2025',
  },
  {
    id: 'client-2',
    contactName: 'James Okafor',
    businessName: 'Okafor & Partners',
    contactEmail: 'james@okaforpartners.com',
    certificateCount: 2,
    avatarInitials: 'JO',
    phone: '(555) 345-6789',
    address: '450 Lexington Ave, Floor 18, New York, NY 10017',
    createdAt: 'Apr 10, 2025',
  },
  {
    id: 'client-3',
    contactName: 'Elena Vásquez',
    businessName: 'Vásquez Construction',
    contactEmail: 'elena@vasquezconstruction.com',
    certificateCount: 6,
    avatarInitials: 'EV',
    phone: '(555) 456-7890',
    address: '820 Industrial Blvd, Austin, TX 78745',
    createdAt: 'Jan 22, 2025',
  },
  {
    id: 'client-4',
    contactName: 'Thomas Webb',
    businessName: 'Webb Industrial Services',
    contactEmail: 'thomas@webbindustrial.com',
    certificateCount: 1,
    avatarInitials: 'TW',
    phone: '(555) 567-8901',
    address: '1200 Manufacturing Way, Cleveland, OH 44114',
    createdAt: 'Jun 5, 2025',
  },
  {
    id: 'client-5',
    contactName: 'Priya Sharma',
    businessName: 'Sharma Tech Solutions',
    contactEmail: 'priya@sharmatech.com',
    certificateCount: 3,
    avatarInitials: 'PS',
    phone: '(555) 678-9012',
    address: '300 Innovation Dr, San Jose, CA 95110',
    createdAt: 'Feb 18, 2025',
  },
  {
    id: 'client-6',
    contactName: 'Daniel Rourke',
    businessName: 'Rourke Logistics',
    contactEmail: 'daniel@rourkelogistics.com',
    certificateCount: 2,
    avatarInitials: 'DR',
    phone: '(555) 789-0123',
    address: '750 Cargo Hub Rd, Memphis, TN 38118',
    createdAt: 'May 12, 2025',
  },
  {
    id: 'client-7',
    contactName: 'Mei-Ling Chen',
    businessName: 'Pacific Rim Exports',
    contactEmail: 'meiling@pacificrimex.com',
    certificateCount: 0,
    avatarInitials: 'MC',
    phone: '(555) 890-1234',
    address: '200 Harbor Dr, San Francisco, CA 94111',
    createdAt: 'Jul 12, 2025',
  },
];

export const INITIAL_CERTIFICATES: Certificate[] = [
  {
    id: 'cert-1',
    clientId: 'client-2',
    certificateNumber: 'COI-2026-00101',
    certificateHolderName: 'Apex Property Holdings LLC',
    certificateHolderAddress: '100 Michigan Ave, Chicago, IL 60603',
    certificateDate: 'Jan 1, 2026',
    insuredName: 'James Okafor',
    additionalInsured: true,
    status: 'active',
    lastUpdated: 'Aug 8, 2026',
    policyType: 'General Liability 2026',
    policyNumber: 'GL-882319-04',
    effectiveDate: 'Jan 1, 2026',
    expirationDate: '2027-01-01',
    generalAggregateLimit: '$5,000,000',
    eachOccurrenceLimit: '$2,000,000',
    fileSize: '1.2 MB',
  },
  {
    id: 'cert-2',
    clientId: 'client-2',
    certificateNumber: 'COI-2026-00102',
    certificateHolderName: 'Chicago Builders Corp',
    certificateHolderAddress: '450 State St, Chicago, IL 60605',
    certificateDate: 'Mar 15, 2026',
    insuredName: 'James Okafor',
    additionalInsured: true,
    status: 'active',
    lastUpdated: 'Aug 8, 2026',
    policyType: "Worker's Comp Policy",
    policyNumber: 'WC-44910-09',
    effectiveDate: 'Mar 15, 2026',
    expirationDate: '2027-03-15',
    generalAggregateLimit: '$1,000,000',
    eachOccurrenceLimit: '$1,000,000',
    fileSize: '980 KB',
  },
  {
    id: 'cert-3',
    clientId: 'client-1',
    certificateNumber: 'COI-2025-00088',
    certificateHolderName: 'Midwest Transport Authority',
    certificateHolderAddress: '800 Railway Plaza, Chicago, IL 60607',
    certificateDate: 'Jun 1, 2025',
    insuredName: 'Mitchell',
    additionalInsured: false,
    status: 'active',
    lastUpdated: 'Jun 2, 2025',
    policyType: 'Commercial Auto 2025',
    policyNumber: 'CA-99381-12',
    effectiveDate: 'Jun 1, 2025',
    expirationDate: '2026-06-01',
    generalAggregateLimit: '$2,000,000',
    eachOccurrenceLimit: '$1,000,000',
    fileSize: '1.4 MB',
  },
  {
    id: 'cert-4',
    clientId: 'client-1',
    certificateNumber: 'COI-2026-00045',
    certificateHolderName: 'Illinois State Development',
    certificateHolderAddress: '200 Capitol Ave, Springfield, IL 62701',
    certificateDate: 'Feb 20, 2026',
    insuredName: 'Done John',
    additionalInsured: true,
    status: 'active',
    lastUpdated: 'Feb 21, 2026',
    policyType: 'Umbrella Policy 2026',
    policyNumber: 'UM-10049-33',
    effectiveDate: 'Feb 20, 2026',
    expirationDate: '2027-02-20',
    generalAggregateLimit: '$10,000,000',
    eachOccurrenceLimit: '$5,000,000',
    fileSize: '760 KB',
  },
  {
    id: 'cert-5',
    clientId: 'client-3',
    certificateNumber: 'COI-2026-00099',
    certificateHolderName: 'Alice Commercial Real Estate',
    certificateHolderAddress: '300 Plaza Way, Austin, TX 78701',
    certificateDate: 'Apr 1, 2026',
    insuredName: 'Alice',
    additionalInsured: false,
    status: 'active',
    lastUpdated: 'Aug 6, 2026',
    policyType: 'Professional Liability',
    policyNumber: 'PL-55102-88',
    effectiveDate: 'Apr 1, 2026',
    expirationDate: '2027-04-01',
    generalAggregateLimit: '$2,000,000',
    eachOccurrenceLimit: '$1,000,000',
    fileSize: '1.1 MB',
  },
  {
    id: 'cert-6',
    clientId: 'client-2',
    certificateNumber: 'COI-2026-00104',
    certificateHolderName: 'Okafor Development',
    certificateHolderAddress: '100 Wall St, New York, NY 10005',
    certificateDate: 'Jan 1, 2026',
    insuredName: 'Okafor',
    additionalInsured: true,
    status: 'active',
    lastUpdated: 'Aug 6, 2026',
    policyType: 'General Liability 2026',
    policyNumber: 'GL-99381-01',
    effectiveDate: 'Jan 1, 2026',
    expirationDate: '2027-01-01',
    generalAggregateLimit: '$5,000,000',
    eachOccurrenceLimit: '$2,000,000',
    fileSize: '1.3 MB',
  },
  {
    id: 'cert-7',
    clientId: 'client-3',
    certificateNumber: 'COI-2026-00210',
    certificateHolderName: 'Austin City Limits Inc',
    certificateHolderAddress: '400 Congress Ave, Austin, TX 78701',
    certificateDate: 'May 10, 2026',
    insuredName: 'Vásquez',
    additionalInsured: true,
    status: 'active',
    lastUpdated: 'Aug 5, 2026',
    policyType: "Builder's Risk Insurance",
    policyNumber: 'BR-44109-22',
    effectiveDate: 'May 10, 2026',
    expirationDate: '2027-05-10',
    generalAggregateLimit: '$5,000,000',
    eachOccurrenceLimit: '$2,500,000',
    fileSize: '2.1 MB',
  },
  {
    id: 'cert-8',
    clientId: 'client-4',
    certificateNumber: 'COI-2025-00112',
    certificateHolderName: 'Cleveland Industrial Hub',
    certificateHolderAddress: '900 Euclid Ave, Cleveland, OH 44115',
    certificateDate: 'Jan 1, 2025',
    insuredName: 'Webbs',
    additionalInsured: false,
    status: 'active',
    lastUpdated: 'Jul 30, 2026',
    policyType: 'General Liability 2025',
    policyNumber: 'GL-33100-09',
    effectiveDate: 'Jan 1, 2025',
    expirationDate: '2026-01-01',
    generalAggregateLimit: '$2,000,000',
    eachOccurrenceLimit: '$1,000,000',
    fileSize: '1.0 MB',
  },
  {
    id: 'cert-9',
    clientId: 'client-5',
    certificateNumber: 'COI-2026-00301',
    certificateHolderName: 'Silicon Tech Partners',
    certificateHolderAddress: '500 Tech Blvd, San Jose, CA 95112',
    certificateDate: 'Jul 1, 2026',
    insuredName: 'Sharma',
    additionalInsured: true,
    status: 'active',
    lastUpdated: 'Aug 7, 2026',
    policyType: 'Cyber Liability Policy',
    policyNumber: 'CY-88310-99',
    effectiveDate: 'Jul 1, 2026',
    expirationDate: '2027-07-01',
    generalAggregateLimit: '$3,000,000',
    eachOccurrenceLimit: '$1,500,000',
    fileSize: '880 KB',
  },
  {
    id: 'cert-10',
    clientId: 'client-6',
    certificateNumber: 'COI-2026-00088',
    certificateHolderName: 'Prologis Distribution Center',
    certificateHolderAddress: '500 Logistics Way, Memphis, TN 38118',
    certificateDate: 'Mar 1, 2026',
    insuredName: 'Rourke',
    additionalInsured: false,
    status: 'active',
    lastUpdated: 'Aug 4, 2026',
    policyType: 'Commercial Property',
    policyNumber: 'CP-44021-99',
    effectiveDate: 'Mar 1, 2026',
    expirationDate: '2027-03-01',
    generalAggregateLimit: '$3,000,000',
    eachOccurrenceLimit: '$1,500,000',
    fileSize: '1.5 MB',
  },
];

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    title: 'General Liability 2026',
    clientName: 'Meridian Group LLC',
    action: 'Certificate uploaded',
    date: 'Aug 8, 2026',
  },
  {
    id: 'act-2',
    title: 'Commercial Property',
    clientName: 'Rourke Logistics',
    action: 'Certificate downloaded',
    date: 'Aug 4, 2026',
  },
  {
    id: 'act-3',
    title: 'General Liability 2026',
    clientName: 'Meridian Group LLC',
    action: 'Certificate uploaded',
    date: 'Aug 8, 2026',
  },
  {
    id: 'act-4',
    title: 'Commercial Property',
    clientName: 'Rourke Logistics',
    action: 'Certificate downloaded',
    date: 'Aug 4, 2026',
  },
  {
    id: 'act-5',
    title: 'Commercial Property',
    clientName: 'Rourke Logistics',
    action: 'Certificate downloaded',
    date: 'Aug 4, 2026',
  },
];
